### ISSUE TITLE
Native dependency 'graphene-1.0' not found while building

### ISSUE THREAD

**Issue by sr1990** [lubosz/gst-plugins-vr#6]
I am trying to build gst-plugins-vr and I get the following problem:

System: Ubuntu 16.04 

The Meson build system
Version: 0.39.1
Source dir: /home/sanil/Desktop/VR/gst-plugins-vr
Build dir: /home/sanil/Desktop/VR/gst-plugins-vr/build
Build type: native build
Project name: gst-plugins-vr
Native c compiler: cc (gcc 5.4.0)
Native cpp compiler: c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getrusage": YES
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gobject-2.0 found: YES 2.48.2

Executing subproject graphene.

Project name: graphene
Native c compiler: cc (gcc 5.4.0)
Checking if "check for -ffast-math" compiles: YES
Checking if "check for -fstrict-aliasing" compiles: YES
Checking if "check for -Wall" compiles: YES
Checking if "check for -Wpointer-arith" compiles: YES
Checking if "check for -Wmissing-declarations" compiles: YES
Checking if "check for -Wformat=2" compiles: YES
Checking if "check for -Wstrict-prototypes" compiles: YES
Checking if "check for -Wmissing-prototypes" compiles: YES
Checking if "check for -Wnested-externs" compiles: YES
Checking if "check for -Wold-style-definition" compiles: YES
Checking if "check for -Wdeclaration-after-statement" compiles: YES
Checking if "check for -Wunused" compiles: YES
Checking if "check for -Wuninitialized" compiles: YES
Checking if "check for -Wshadow" compiles: YES
Checking if "check for -Wmissing-noreturn" compiles: YES
Checking if "check for -Wmissing-format-attribute" compiles: YES
Checking if "check for -Wredundant-decls" compiles: YES
Checking if "check for -Wlogical-op" compiles: YES
Checking if "check for -Wcast-align" compiles: YES
Checking if "check for -Wno-unused-local-typedefs" compiles: YES
Checking if "check for -Werror=implicit" compiles: YES
Checking if "check for -Werror=init-self" compiles: YES
Checking if "check for -Werror=main" compiles: YES
Checking if "check for -Werror=missing-braces" compiles: YES
Checking if "check for -Werror=return-type" compiles: YES
Checking if "check for -Werror=array-bounds" compiles: YES
Checking if "check for -Werror=write-strings" compiles: YES
Has header "stdlib.h": YES
Has header "stdint.h": YES
Has header "stdbool.h": YES
Has header "memory.h": YES
Checking for function "aligned_alloc": YES
Checking for function "memalign": NO
Checking for function "posix_memalign": YES
Checking for function "sincosf": YES
Library m found: YES
Dependency threads found: YES
Program g-ir-scanner found: NO
Checking if "SSE intrinsics" compiles: YES
Checking if "GCC vector intrinsics" compiles: YES
Checking if "ARM NEON intrinsics" compiles: NO
Configuring config.h using configuration
Configuring graphene-config.h using configuration
Configuring graphene-version.h using configuration
Also couldn't find a fallback subproject in subprojects/graphene for the dependency graphene-1.0

Meson encountered an error in file meson.build, line 15, column 0:
Native dependency 'graphene-1.0' not found
EXIT meson return 1
Makefile won't be generated
--------------------------------------------------------------------------------------------------------------------------------------
When I try to install graphene, I get the following: 

pip install "graphene>=1.0"
Collecting graphene>=1.0
Collecting graphql-relay>=0.4.5 (from graphene>=1.0)
Collecting promise>=1.0.1 (from graphene>=1.0)
Collecting graphql-core>=1.0.1 (from graphene>=1.0)
Collecting six>=1.10.0 (from graphene>=1.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting typing (from promise>=1.0.1->graphene>=1.0)
Installing collected packages: six, typing, promise, graphql-core, graphql-relay, graphene
Successfully installed graphene-1.3 graphql-core-1.0.1 graphql-relay-0.4.5 promise-1.0.1 six-1.10.0 typing-3.6.1
------------------------------------------------------------------------------------------------------------------------------------------
Please let me know how I can rectify this issue.
Thanks

**Comment by tamimcse** [comment]
I'm facing same issue. Any solution to this?

**Comment by lubosz** [comment]
The graphene in pip is the wrong one. The dependency is this:
https://github.com/ebassi/graphene

Not this python project:
https://github.com/graphql-python/graphene

As I can see the meson build tries to build graphene, but fails. I wonder on which platform you are trying to do that? Best would be to use graphene from your package manager.

For example:

Ubuntu
https://launchpad.net/ubuntu/zesty/+source/graphene

Arch
https://www.archlinux.org/packages/extra/x86_64/graphene/

Otherwise you can install it from source manually with the above github link.

**Comment by tamimcse** [comment]
Thanks for the help! I'm using Ubuntu Gnome 16.04.

Could you please provide me with the PPA URL? I don't seem to figure out from the website.

**Comment by lubosz** [comment]
It seems that you don't need a ppa for graphene, it is in the regular ubuntu repository. Make sure you install the headers as well (-dev package).

**Comment by tamimcse** [comment]
**sudo apt-get install graphene-dev** doesn't work here. Could you please suggest?

**Comment by sr1990** [comment]
@lubosz worked for me. Thanks! 
@tamimcse Try getting graphene from: https://github.com/ebassi/graphene

**Comment by lubosz** [comment]
@tamimcse If the -dev package is not available, the headers are probably in the regular package. I cannot check, since I currently don't have access to an Ubuntu system.

**Comment by 238Ver** [comment]
> The graphene in pip is the wrong one. The dependency is this: https://github.com/ebassi/graphene
> 
> Not this python project: https://github.com/graphql-python/graphene
> 
> As I can see the meson build tries to build graphene, but fails. I wonder on which platform you are trying to do that? Best would be to use graphene from your package manager.
> 
> For example:
> 
> Ubuntu https://launchpad.net/ubuntu/zesty/+source/graphene
> 
> Arch https://www.archlinux.org/packages/extra/x86_64/graphene/
> 
> Otherwise you can install it from source manually with the above github link.

It works！ Thanks a lot
