### ISSUE TITLE
gst_gl_framebuffer_new: assertion 'gst_gl_context_get_current () == context' failed

### ISSUE THREAD

**Issue by tamimcse** [lubosz/gst-plugins-vr#9]
**GST_PLUGIN_PATH=/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0 gst-launch-1.0 vrtestsrc ! video/x-raw\(memory:GLMemory\), width=1920, height=1080 ! glimagesink** command is giving following output:

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'sink': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayX11\)\ gldisplayx11-0";

** (gst-launch-1.0:3379): CRITICAL **: gst_gl_framebuffer_new: assertion 'gst_gl_context_get_current () == context' failed
Caught SIGSEGV
#0  0x00007f1787692b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f1787bc838c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1787bc8712 in g_main_loop_run ()
#3  0x00007f17881259b9 in gst_bus_poll (bus=bus@entry=0x212ac00, 
#4  0x00000000004048a8 in event_loop (pipeline=0x2468260, 
#5  0x00000000004038a3 in main (argc=8, argv=0x7ffeabbf80c8)

**Comment by lubosz** [comment]
I could reproduce the crash.
Should be fixed with https://github.com/lubosz/gst-plugins-vr/commit/bd2aaf047b2ee5fea5298d6a6a8f706392d037e5

**Comment by tamimcse** [comment]
Now I'm getting another error: syntax error near unexpected token `('
